server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/portdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

app:
  kafka:
    enabled: ${APP_KAFKA_ENABLED:false}
    topic:
      yard-events: ${APP_KAFKA_TOPIC_YARD_EVENTS:yard-events}

jwt:
  secret: ${JWT_SECRET:Y2hhbmdlbWUtc2VjcmV0LXNlY3JldC1zZWNyZXQ=}
  issuer: hungnv-backend
  expiration-seconds: 36000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

mail:
  host: ${MAIL_HOST:localhost}
  port: ${MAIL_PORT:1025}
  username: ${MAIL_USER:}
  password: ${MAIL_PASS:}
  properties:
    mail:
      smtp:
        auth: false
        starttls:
          enable: false
